GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py:68: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py:397: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
Traceback (most recent call last):
  File "/home/zheng709/model-immunization-cond-num/main.py", line 91, in <module>
    trainer.fit(model, data_module)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 974, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 107, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 198, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/zheng709/model-immunization-cond-num/dataset.py", line 295, in setup
    self.d1_train = create_dataset("imagenet", root=self.d1_path, split="train")
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/timm/data/dataset_factory.py", line 221, in create_dataset
    ds = ImageDataset(
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/timm/data/dataset.py", line 36, in __init__
    reader = create_reader(
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/timm/data/readers/reader_factory.py", line 38, in create_reader
    assert os.path.exists(root)
AssertionError
