2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_setup.py:_flush():81] Configure stats pid to 836080
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_setup.py:_flush():81] Loading settings from /home/zheng709/.config/wandb/settings
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_setup.py:_flush():81] Loading settings from /home/zheng709/model-immunization-cond-num/wandb/settings
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_init.py:setup_run_log_directory():703] Logging user logs to ./wandb/run-20250608_030431-rvisd7eu/logs/debug.log
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to ./wandb/run-20250608_030431-rvisd7eu/logs/debug-internal.log
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_init.py:init():831] calling init triggers
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-08 03:04:31,857 INFO    MainThread:836080 [wandb_init.py:init():872] starting backend
2025-06-08 03:04:32,064 INFO    MainThread:836080 [wandb_init.py:init():875] sending inform_init request
2025-06-08 03:04:32,069 INFO    MainThread:836080 [wandb_init.py:init():883] backend started and connected
2025-06-08 03:04:32,074 INFO    MainThread:836080 [wandb_init.py:init():956] updated telemetry
2025-06-08 03:04:32,080 INFO    MainThread:836080 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-08 03:04:32,640 INFO    MainThread:836080 [wandb_init.py:init():1032] starting run threads in backend
2025-06-08 03:04:32,693 INFO    MainThread:836080 [wandb_run.py:_console_start():2453] atexit reg
2025-06-08 03:04:32,694 INFO    MainThread:836080 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-08 03:04:32,694 INFO    MainThread:836080 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-08 03:04:32,694 INFO    MainThread:836080 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-08 03:04:32,696 INFO    MainThread:836080 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-08 03:04:32,757 INFO    MainThread:836080 [wandb_run.py:_config_callback():1358] config_cb None None {'task': 'regression', 'feature_extractor_type': 'linear', 'feat_size': 79, 'hidden_size': 79, 'lambda_kappa': 1, 'lambda_r1': 100, 'lambda_r2': '1e7', 'lambda_reg': 1, 'lr': '5e-3'}
2025-06-08 03:05:28,284 ERROR   MainThread:836080 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-06-08 03:05:28,285 ERROR   MainThread:836080 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-06-08 03:05:28,285 ERROR   MainThread:836080 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 184, in GetCurrentTime
    self.FromDatetime(datetime.datetime.now(tz=datetime.timezone.utc))
  File "/home/zheng709/miniconda3/envs/model-immu/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 283, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
